name = "aiken-lang/mint"
version = "0.0.0"
compiler = "v1.0.28-alpha"
plutus = "v2"
license = "Apache-2.0"
description = "Aiken contracts for project 'aiken-lang/mint'"

[repository]
user = "aiken-lang"
project = "mint"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.1.0"
source = "github"
